### ISSUE TITLE
帅哥 这里版本不对， 没有1.0.1

### ISSUE THREAD

**Issue by long0419** [EYHN/rust-filament#1]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1064859/162882282-63e1b930-edd4-4756-a9fa-442093992584.png">
帅哥 这里版本不对， 没有1.0.1

**Comment by EYHN** [comment]
这不是吗 https://crates.io/crates/russimp-sys-static/versions

**Comment by long0419** [comment]
![image](https://user-images.githubusercontent.com/1064859/162892039-cded3e95-f03d-41ac-8500-8dede6e3b6ba.png)
这里的版本 也不对吧

**Comment by EYHN** [comment]
版本是对的 build的时候会从github release下载预构建包，确保你网络通畅

**Comment by long0419** [comment]
有联系方式吗？

**Comment by EYHN** [comment]
https://t.me/EEYHN
